### ISSUE TITLE
Add pull request templates and CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by Pranav016** [akshitagupta15june/vehicle_speed_estimator#11]
* Pull request template would help the maintainer review the PRs more effectively and efficiently. 
* Add CODE_OF_CONDUCT for NWoC participants. 

@akshitagupta15june If approved I would like to work on this issue under NJACK WoC :)

**Comment by Pranav016** [comment]
@akshitagupta15june Can I get this issue assigned? 😄

**Comment by akshitagupta15june** [comment]
Yes work on it.
