### ISSUE TITLE
fix anti-patterns and optimize code performance

### ISSUE THREAD

**Issue by tusharnankani** [akshitagupta15june/vehicle_speed_estimator#24]
**Describe the bug**
In reference to PR #22, that was unnecessarily closed because an issue wasn't raised ^_^

**Comment by akshitagupta15june** [comment]
ok @tusharnankani will look at your pr

**Comment by tusharnankani** [comment]
closed via #22

**Comment by akshitagupta15june** [comment]
Thankyou for your contribution @tusharnankani
