### ISSUE TITLE
Develop a Python GUI for displaying Results.

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/vehicle_speed_estimator#7]
Develop a Python GUI for displaying Results.
A Interactive GUI application using python (Tkinter) to show results

**Comment by Vrindagupta6828** [comment]
@akshitagupta15june Please assign me this.

**Comment by akshitagupta15june** [comment]
ok assigning

**Comment by akshitagupta15june** [comment]
@Vrindagupta6828 Join Discord channel for discussion or queries.
discord.gg/ejpggpfy

**Comment by Vrindagupta6828** [comment]
@akshitagupta15june It is showing invalid invite.
